// jkcoxson
// This file is pregenerated by the camel-package tool.

fn main() {
    let pkg_name: String = "cargo-camel-package";
    let binary = include_bytes!("/Users/jacksoncoxson/Local_Code/camel_package/target/aarch64-apple-darwin/release/cargo-camel-package");
    println!("")
}
