// jkcoxson
// This file is pregenerated by the camel-package tool.

use cursive::{views::Dialog, Cursive, CursiveExt};

fn main() {
    // General setup
    let pkg_name: String = camel_insert_package_name!();
    let binary = camel_insert_binary!();
    let binary_install_path = camel_insert_install_path!();
    let license = camel_insert_license!();
    println!("Starting installer for {}", pkg_name);

    let mut siv = Cursive::default();
    let (sender, receiver) = std::sync::mpsc::channel();
    let welcome_prompt = Dialog::new().title("Installer").content(
        Dialog::text(
            format!(
                "Welcome to the installer for {}.\n\
            You will be guided through the installation process.\n\n\
            This installer has the ability to cause damage to your system.\n\
            If you do not trust the source of this installer, exit now.\n\
            ",
                pkg_name
            )
            .as_str(),
        )
        .button("Continue", move |s| {
            sender.send(());
            s.pop_layer();
        }),
    );
    siv.add_layer(welcome_prompt);
    siv.run();
    receiver.recv().unwrap();

    // Show the license
    if license != "".to_string() {
        let (sender, receiver) = std::sync::mpsc::channel();
        let license_prompt = Dialog::new()
            .title("License")
            .content(Dialog::text(license).button("Continue", move |s| {
                sender.send(());
                s.pop_layer();
            }));
        siv.add_layer(license_prompt);
        siv.run();
        receiver.recv().unwrap();
    }
}

pub struct Lib {
    pub name: String,
    pub path: String,
    pub install_path: String,
    pub variable_path: bool,
    pub optional: bool,
}

pub struct Binary {
    pub name: String,
    pub path: String,
    pub optional: bool,
}
